[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "VeFRA"
version = "0.1" 
description = "VeFRA - Vention Financial Analyzer, a Q&A system working with 10-Q financial reports."
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
extend-select = ["UP"]

extend-safe-fixes = ["UP006", "UP007"]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
markers = [
    "real_api: marks tests that make real API calls to external services (e.g., OpenAI)",
]
asyncio_mode = "auto"